package com.myspace.userstore;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Store implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String itemName;
	private java.lang.Integer quantity;
	private java.lang.Float price;
	private java.lang.Boolean saleNotAllowed;

	private java.lang.String itemType;

	public Store() {
	}

	public java.lang.String getItemName() {
		return this.itemName;
	}

	public void setItemName(java.lang.String itemName) {
		this.itemName = itemName;
	}

	public java.lang.Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(java.lang.Integer quantity) {
		this.quantity = quantity;
	}

	public java.lang.Float getPrice() {
		return this.price;
	}

	public void setPrice(java.lang.Float price) {
		this.price = price;
	}

	public java.lang.Boolean getSaleNotAllowed() {
		return this.saleNotAllowed;
	}

	public void setSaleNotAllowed(java.lang.Boolean saleNotAllowed) {
		this.saleNotAllowed = saleNotAllowed;
	}

	public java.lang.String getItemType() {
		return this.itemType;
	}

	public void setItemType(java.lang.String itemType) {
		this.itemType = itemType;
	}

	public Store(java.lang.String itemName, java.lang.Integer quantity,
			java.lang.Float price, java.lang.Boolean saleNotAllowed,
			java.lang.String itemType) {
		this.itemName = itemName;
		this.quantity = quantity;
		this.price = price;
		this.saleNotAllowed = saleNotAllowed;
		this.itemType = itemType;
	}

}
